[2025-09-18T20:11:25.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T20:11:25.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_forecast_stock.wait_for_etl manual__2025-09-18T20:11:24.208151+00:00 [queued]>
[2025-09-18T20:11:25.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_forecast_stock.wait_for_etl manual__2025-09-18T20:11:24.208151+00:00 [queued]>
[2025-09-18T20:11:25.323+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-18T20:11:25.329+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_etl> on 2025-09-18 20:11:24.208151+00:00
[2025-09-18T20:11:25.333+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=12264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-18T20:11:25.334+0000] {standard_task_runner.py:64} INFO - Started process 12266 to run task
[2025-09-18T20:11:25.334+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_forecast_stock', 'wait_for_etl', 'manual__2025-09-18T20:11:24.208151+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/ml_forecast_stock.py', '--cfg-path', '/tmp/tmp6ltybe28']
[2025-09-18T20:11:25.335+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask wait_for_etl
[2025-09-18T20:11:25.360+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_forecast_stock.wait_for_etl manual__2025-09-18T20:11:24.208151+00:00 [running]> on host 11e1994bdecf
[2025-09-18T20:11:25.406+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data226' AIRFLOW_CTX_DAG_ID='ml_forecast_stock' AIRFLOW_CTX_TASK_ID='wait_for_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T20:11:24.208151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T20:11:24.208151+00:00'
[2025-09-18T20:11:25.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T20:11:25.407+0000] {baseoperator.py:400} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-09-18T20:11:25.410+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_upsert'] in dag "etl_yfinance_stock" on 2025-09-18T20:11:24.208151+00:00 ... 
[2025-09-18T20:11:25.421+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T20:11:25.422+0000] {taskinstance.py:2506} INFO - Skipping due to soft_fail is set to True.
[2025-09-18T20:11:25.426+0000] {taskinstance.py:1206} INFO - Marking task as SKIPPED. dag_id=ml_forecast_stock, task_id=wait_for_etl, run_id=manual__2025-09-18T20:11:24.208151+00:00, execution_date=20250918T201124, start_date=20250918T201125, end_date=20250918T201125
[2025-09-18T20:11:25.473+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T20:11:25.478+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2025-09-18T20:11:25.485+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T20:11:25.487+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
